### PR TITLE
added dotStyle scaleup

### PR DESCRIPTION
**Pull request by Sivli-Embir**
From: http://tympanus.net/Development/DotNavigationStyles/

A nav for scrolling though collections, or any kind of position indicator.

``` styl
@import s(basePath, dotStyle)
cpDotStyleScaleup(brandColor, bgColor) //edit: now cpDotStyleScaleup calls cpDotStyle internally 
```

``` jade
template(name='dotStyle')
  .dotstyle.dotstyle-scaleup
    h2 Dot Nav
    ul
      each example
        li(class="{{active}}"): a
```

``` coffee
Template.dotStyle.onCreated ->
  @active = new ReactiveVar(1)  

Template.dotStyle.helpers
  example: -> [ #replace example with a Collection Cursor
    {id:1}
    {id:2}
    {id:3}
    {id:4}
    {id:5}
  ]
  active: -> 'active' if Template.instance().active.get() is @id

Template.dotStyle.events
  'click a': (e,t) ->
    e.preventDefault()
    Template.instance().active.set @id
```

### CODE REVIEW

**Comment by Sivli-Embir** [comment]
Figured I would save time and just go strait to the PR. I have not optimized, still learning the tools.

**Comment by Sivli-Embir** [comment]
Ack, I did it again. I have to bump the version number locally to see the changes. CSS does not hot code push in packages for some reason.

**Comment by PEM--** [comment]
I got the same issue on the version number. My stance is to take a former one, let Isobuild compile and revert the number back. Easy.

For the automatic call to `cpDotStyle`, I'm not too found of it. In case, I would like to add a `dotStyle` for some part of my templates and another one for other template, that would create twice the base CSS styles.

Where do you think we should put these? In the 'Others' category? I definitely should start something for a better menu.

**Comment by Sivli-Embir** [comment]
Yeah I was doing that with the version number, I just forgot to put it back before I pushed.

That makes sense. Is there no way to say if added/called already then skip? Open to whatever, but both my PRs had many other options that used the same core css.

"Other" works for now, best to move them as needed. It is an odd mix of radio buttons and nav. It is not a radio and I don't feel that is how it should be used, but it could be. But its not really a nav option.

**Comment by PEM--** [comment]
The `menu` and `menuitem` would have been great... Unfortunately, they are poorly implemented by browser vendors. Well, at least, the `ul` and `li` is a well known pattern.

**Comment by PEM--** [comment]
Published. I've also added 2 additional styles :smile:

**Comment by Sivli-Embir** [comment]
Nice! Thanks ^_^

**Comment by Sivli-Embir** [comment]
Focus state is buggy on Scale up and Stroke. This was my bad. If you click the element it remains focused and you can't tell which one has the `active` class. Clicking away, losing focus, fixes it.

**Comment by PEM--** [comment]
Looking nice to me. If you want to make some additions, do not hesitate. We are starting to have a nice collection.

**Pull request merged**
