### PR TITLE
added cpButtonMorphOverlay for init review

### PR DESCRIPTION
**Pull request by Sivli-Embir**
This still needs a good bit of work. Currently I am only adding overlay (it seemed the easiest).

``` jade
template(name="MorphButton")
  .morph-button.morph-button-overlay.morph-button-fixed
    button click me
    .morph-content hi there!
```

``` coffee
#With blaze
Template.MorphButton.events
  'click': -> Template.instance().toggle()

Template.MorphButton.onRendered ->
  @toggle = =>
    buttonPos = @$('button')[0].getBoundingClientRect()
    el = @$('.morph-button')
    setTimeout (=>
      @$('.morph-content').css 
        left: buttonPos.left + 'px'
        top: buttonPos.top + 'px'
      if @expanded
        el.removeClass 'open'
      else
        setTimeout (=> el.addClass 'open'), 25
      @expanded = !@expanded
    ), 25
    return
```

### CODE REVIEW

**Comment by Sivli-Embir** [comment]
Agreed, I did not do any logic clean up (other then using meteor jQuery for the example).

Those modals are sweet! That said the selling point on the buttons are that they conform to [Material Design - Responsive Interactions](http://www.google.com/design/spec/animation/responsive-interaction.html). I don't necessarily agree with all of Google's spec but IMO there is a lot of good principles in it. Animations should originate from the activator whenever possible.

**Comment by PEM--** [comment]
We are definitely not only sharing aesthetics and codes!

**Comment by PEM--** [comment]
And published!

**Comment by Sivli-Embir** [comment]
Nice! Quick note, you may want to switch up that template event if it is going to include more then just the button/model. Currently any page level click fires the modal.

``` coffee
#from
Template.offScreens.events
  click: (e, t) -> t.toggle()
#to
Template.offScreens.events
  'click .morph-button': (e, t) -> t.toggle()
```

**Comment by Sivli-Embir** [comment]
Also, while we are looking at it. Do you know of any way we can make this responsive, vs fixed width/hight? Since we have to use JS anyway I feel that is reasonable.

**Comment by PEM--** [comment]
Ha ha. I was just toying with it when you were writing this.

I've found a weird issue with [Wow.js](http://mynameismatthieu.com/WOW/) and the behavior of the `getBoundingClientRect`. I think I will have to investigate around this. It's bit late out there in France. I will just publish a new fresh release with your tip and without the page transition.

**Comment by Sivli-Embir** [comment]
Ok cool and no worries or rush. Nice work all around, enjoy your rest ^_^

**Comment by PEM--** [comment]
For making it responsive, we should remove the styles within the `.morph-content` letting the user decide what he wants to put within. Some Jeet magic would be nice.

**Pull request merged**
